### GET all products
GET http://localhost:5000/api/products
Accept: application/json

###

### GET single products (replace {{id}} with an actual document id)
GET http://localhost:5000/api/products/AtKifug6bj8lCC7q8ImB
Accept: application/json

###

### CREATE products (should succeed)
POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "Demo2 products",
  "price": 25.5,
  "description": "Sample item for testing",
  "image": "https://via.placeholder.com/150"
}

###

### CREATE invalid products (should error: price invalid)
POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "Bad Product",
  "price": -10,
  "description": "Should trigger validation error",
  "image": "https://via.placeholder.com/150"
}

###

### CREATE invalid product (should error: name missing)
POST http://localhost:5000/api/products
Content-Type: application/json

{
  "price": 10,
  "description": "No name here",
  "image": "https://via.placeholder.com/150"
}

###

### UPDATE product (should succeed)
PUT http://localhost:5000/api/products/SNoeuUSkOWZkryEyY8Ba
Content-Type: application/json

{
  "name":"test",
  "price": 29.99,
  "description": "Updated description"
}


### DELETE product (should succeed)
DELETE http://localhost:5000/api/products/220XMNROFMTZtwSteS3z
###

### DELETE non-existent product (should error)
DELETE http://localhost:5000/api/products/fake-id
